language: java
matrix:
  include:
    - name: "Linux JDK8"
      os: linux
      dist: trusty
      jdk:
        - openjdk8
      env:
        - TRAVIS_DIST_NAME="trusty"
    - name: "MacOS JDK8"
      os: osx
      osx_image: xcode9.3
#    - name: "Windows" --- Not yet supported
#      os: windows
#      jdk:
#        - openjdk8

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - cd $WD

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f '/usr/local/include/c++'; brew install r libxml2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [[ "$TRAVIS_DIST_NAME" == "trusty" ]]; then echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_DIST_NAME" == "xenial" ]]; then echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_DIST_NAME" == "trusty" ]]; then sudo add-apt-repository -s -y ppa:marutter/c2d4u; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install r-recommended pandoc --allow-unauthenticated -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pandoc; fi
  - mkdir libR; R -e "install.packages(c('devtools','usethis'),repos = 'http://cran.us.r-project.org',lib='libR')"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f '/usr/local/include/c++'; brew install ant; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ant -y; fi
  
script: 
  - ant test

before_deploy:
  - ant clean dist
  - cd dist; zip -r ../algorithm-GradientDescent.zip *; cd ..
  - ant install
  - zip -r FunzR-GradientDescent.zip FunzR-GradientDescent
  
deploy:
  provider: releases
  api_key:
    secure: OUtp+0tdLeJOAF2hxi296xZQehcviDGw2hBAOhskkT/X65K5NVzf6BO2IEnMv/k99C7tJQtj0iRr0HhDrx2RVCwO98SX5+LGh+P/8DqhMtCMG55zBxS4ELB6McngCVMCGnSdV2XZWM/ElVf0Zg044dFWn97qnuphnm05Jro4ahWU1E+hzXMNurJzINHbJZ86bHnPTgbdP0ENQuympp+pW1X75O1Hzkcfsy6h75btOifqX2c3Y+jJS1gfGX9qkq4fVeO3C9EhfF1/VN35ChRq/M02c03hg/wF0YghO2XuGg76/VYKbLJkPhymh2jUCEa5utjyM2Dtri4Qkb/cgerM0eisBWgkY/jXiYLKV96FgAEiWBcTuaI07hhBMQOdf3EubpUuB8eMNaaZKkV+Q7R04JNX14+Owqec+o6g4tK+5eZz2lF4LPl4BrKX1coPVRZCcxhgPyL/+wIS/g+RFQ6a7Xh+UQ1dZjDyU2/bqMXfPS6FH/5nC1mY6RZnWbgb3QYfZJfYEV9OXo5kNANY8+nsEURixYyXwXAqy3TZjl0XPHnwNJeCXH9WEhcvQ34Npxp9bv40WDosPgw85VSNYwz2N00QeKh3oBdk+RPdC9TACSqFyUk9iWla3rkVa0pYAdUT+EPLvy7zsRRmCJ1yRMjOTrwrI5kY2kvFUdgvDqWJPdY=
  file_glob: true
  file:
    - FunzR-*.zip
    - algorithm-*.zip
  on:
    tags: true
    branch: master
  skip_cleanup: true
  overwrite: true
