language: minimal
cache:
  directories:
    - $HOME/.jabba/

matrix:
  include:
    - name: "Linux JDK8"
      os: linux
      dist: xenial
      env:
        - JDK="adopt@1.8"
    - name: "Linux JDK11"
      os: linux
      dist: xenial
      env:
        - JDK="openjdk@1.11"
    - name: "Linux JDK13"
      os: linux
      dist: xenial
      env:
        - JDK="openjdk@1.13"
# Vary OS        
    - name: "MacOS JDK11"
      os: osx
      osx_image: xcode10.1
      env:
        - JDK="openjdk@1.11"
    - name: "Windows JDK11"
      os: windows
      env:
        - JDK="openjdk@1.11"

env:
  global:
    # Convenience variables for shortening commands
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis" 
    
before_install:
  # Check out the script set
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export HOMEBREW_NO_AUTO_UPDATE=1; brew update; brew install ant; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ant -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install ant -y; fi

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - cd $WD

before_script:
  - >  
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/" | sudo tee -a /etc/apt/sources.list;
    sudo apt-get update -qq --allow-unauthenticated; 
    sudo apt-get install r-recommended pandoc --allow-unauthenticated -y; 
    sudo apt-get install libglu1-mesa-dev libglu1-mesa-dev libfreetype6-dev --allow-unauthenticated -y; 
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    if [ ! -d "/usr/local/Cellar/r/3.6.3_2" ]; then 
    wd=$PWD;
    cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core; git reset --hard c3a244c627e; git checkout -b r-3.6.3;
    cd $wd;
    brew reinstall r;
    fi;
    export PATH=$PATH:/usr/local/Cellar/r/3.6.3_2/bin;
    echo "" >> ~/.bashrc; echo "export PATH=$PATH:/usr/local/Cellar/r/3.6.3_2/bin;" >> ~/.bashrc;
    brew install pandoc;
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    echo "ls C:/Program Files/R/R-3.6.0/bin:"; ls "C:/Program Files/R/R-3.6.0/bin";
    echo "ls /c/Program Files/R/R-3.6.0/bin:"; ls "/c/Program Files/R/R-3.6.0/bin";
    if [ ! -d "/c/Program Files/R/R-3.6.0/bin" ]; then 
    travis_wait choco install r --version 3.6 -y;
    tail -100 /c/ProgramData/chocolatey/logs/chocolatey.log;
    fi;
    echo "ls /c/Program Files/R/R-3.6.0/bin:"; ls "/c/Program Files/R/R-3.6.0/bin";
    export PATH=$PATH:"/c/Program Files/R/R-3.6.0/bin";
    echo "PATH/bash:"$PATH;
    echo "PATH/cmd:"`cmd.exe //C 'echo %PATH%'`;
    cmd.exe //C "R --version";
    choco install pandoc;
    fi
  - mkdir libR; R -e "install.packages(c('devtools','usethis'),repos = 'http://cran.us.r-project.org',lib='libR')"
  
script: 
  - ant test

before_deploy:
  - ant clean dist
  - cd dist; zip -r ../algorithm-GradientDescent.zip *; cd ..
  - ant install
  - zip -r FunzR-GradientDescent.zip FunzR-GradientDescent
  
deploy:
  provider: releases
  api_key:
    secure: OUtp+0tdLeJOAF2hxi296xZQehcviDGw2hBAOhskkT/X65K5NVzf6BO2IEnMv/k99C7tJQtj0iRr0HhDrx2RVCwO98SX5+LGh+P/8DqhMtCMG55zBxS4ELB6McngCVMCGnSdV2XZWM/ElVf0Zg044dFWn97qnuphnm05Jro4ahWU1E+hzXMNurJzINHbJZ86bHnPTgbdP0ENQuympp+pW1X75O1Hzkcfsy6h75btOifqX2c3Y+jJS1gfGX9qkq4fVeO3C9EhfF1/VN35ChRq/M02c03hg/wF0YghO2XuGg76/VYKbLJkPhymh2jUCEa5utjyM2Dtri4Qkb/cgerM0eisBWgkY/jXiYLKV96FgAEiWBcTuaI07hhBMQOdf3EubpUuB8eMNaaZKkV+Q7R04JNX14+Owqec+o6g4tK+5eZz2lF4LPl4BrKX1coPVRZCcxhgPyL/+wIS/g+RFQ6a7Xh+UQ1dZjDyU2/bqMXfPS6FH/5nC1mY6RZnWbgb3QYfZJfYEV9OXo5kNANY8+nsEURixYyXwXAqy3TZjl0XPHnwNJeCXH9WEhcvQ34Npxp9bv40WDosPgw85VSNYwz2N00QeKh3oBdk+RPdC9TACSqFyUk9iWla3rkVa0pYAdUT+EPLvy7zsRRmCJ1yRMjOTrwrI5kY2kvFUdgvDqWJPdY=
  file_glob: true
  file:
    - FunzR-*.zip
    - algorithm-*.zip
  on:
    tags: true
    branch: master
  skip_cleanup: true
  overwrite: true
